sonar.projectName=ApertureCore
sonar.sourceEncoding=UTF-8

sonar.sources=app,server
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts

sonar.exclusions=.nuxt/**,.output/**,coverage/**,node_modules/**,public/**,docker/**,scripts/**,server/database/migrations/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
